"""add payment_date to bills

Revision ID: 5d67bdbeefe1
Revises: 
Create Date: 2026-01-14 10:56:25.625875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d67bdbeefe1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('payment_date', sa.Date(), nullable=True))
    op.drop_column('bills', 'paymend_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('paymend_date', sa.DATE(), nullable=True))
    op.drop_column('bills', 'payment_date')
    # ### end Alembic commands ###
